# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='json',
            field=models.CharField(max_length=8192),
        ),
    ]
