# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181106_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='client_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
